# Generated by Django 5.0.2 on 2024-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='rasm/images')),
                ('nomi', models.CharField(max_length=200)),
                ('hotelnomi', models.CharField(max_length=200)),
                ('narxi', models.CharField(max_length=222)),
                ('text', models.TextField()),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
    ]
